"""
Writer Agent — generates a polished, formatted Markdown report.
Takes analysis output and produces final human-readable content.
"""

import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))
MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")

SYSTEM_PROMPT = """You are an expert technical writer and report generation agent.
Given an analysis, your job is to produce a comprehensive, well-structured Markdown report.

Your report MUST include:
- A clear title (# heading)
- An executive summary
- Key findings sections with ## headings
- Data points and statistics with proper formatting
- Bullet points and numbered lists where appropriate
- A conclusion section
- A "Generated by Maestro AI" footer

Write in a professional, clear, and engaging tone.
Format for maximum readability.
"""


def write_report(instruction: str, analysis: str = "", retrieved_data: str = "") -> str:
    """
    Generate a formatted Markdown report from analysis and retrieved data.
    Returns final Markdown string.
    """
    context_parts = []
    if retrieved_data:
        context_parts.append(f"Retrieved Information:\n{retrieved_data}")
    if analysis:
        context_parts.append(f"Analysis:\n{analysis}")

    user_content = instruction
    if context_parts:
        user_content = f"{instruction}\n\n{'---'.join(context_parts)}"

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_content},
        ],
        temperature=0.4,
        max_tokens=3000,
    )
    return response.choices[0].message.content.strip()
